# -*- coding: utf-8 -*-
from flask import Flask, Response, render_template
app = Flask(__name__, static_url_path='')

@app.route("/", methods=["GET"])
def home() -> Response:
    """The home route.

    This view serves the HTML page that is the basis of the app, that will
    be generated by a ReactJS front end.

    Returns
    -------
    Response
        The response here will be an HTML template. Right now it'll be a
        static HTML file, but soon will be generated by React.
    """
    return render_template('index.html')
