# -*- coding: utf-8 -*-
import os
from flask_api import FlaskAPI
from flask_cors import CORS
from flask_pymongo import PyMongo

app = FlaskAPI(__name__)
app.config['MONGO_URI'] = os.environ.get(
    'MONGO_URI',
    'mongodb://localhost:27017/tasksdb'
)
mongo = PyMongo(CORS(app))
prefix = '/api/v1'

@app.route(f'{prefix}/tasks')
def get_tasks() -> dict:
    """The home route.

    This view serves the HTML page that is the basis of the app, that will
    be generated by a ReactJS front end.

    Returns
    -------
    Response
        The response here will be an HTML template. Right now it'll be a
        static HTML file, but soon will be generated by React.
    """
    return []